// Settings registration and access
export {
  CLIENT_SHEET_ENHANCEMENTS_SETTING,
  CLIENT_SHOW_LOG_USED_TOGGLE_SETTING,
  CLIENT_CHARACTER_LOG_MAX_HEIGHT_SETTING,
  CLIENT_CHARACTER_MILESTONE_MAX_HEIGHT_SETTING,
  WORLD_ENABLE_TRAUMA_RULES_SETTING,
  WORLD_ENABLE_SCAR_RULES_SETTING,
  WORLD_TRAITS_MODE_SETTING,
  WORLD_SIMPLE_TRAITS_SETTING,
  TRAITS_MODE_ITEM,
  TRAITS_MODE_SIMPLE,
  SIMPLE_TRAIT_MAX_LEN,
  CLIENT_ENABLE_LCARS_MODE_SETTING,
  registerClientSettings,
  areSheetEnhancementsEnabled,
  shouldShowLogUsedToggle,
  getCharacterLogMaxHeightSetting,
  getCharacterMilestoneMaxHeightSetting,
  areTraumaRulesEnabled,
  areScarRulesEnabled,
  getTraitsMode,
  areSimpleTraitsEnabled,
  sanitizeSimpleTraitText,
  getSimpleTraits,
  setSimpleTraits,
  isLcarsModeEnabled,
} from "./clientSettings.js";

export {
  FOCUS_PICKER_CUSTOM_COMPENDIUM_SETTING,
  TALENT_PICKER_CUSTOM_COMPENDIUM_SETTING,
  TALENT_PICKER_CUSTOM_FOLDER_FILTER_SETTING,
  parseCompendiumPackKeys,
  registerFocusPickerSettings,
  registerTalentPickerSettings,
  registerCompendiumPickerMenu,
  getFocusPickerCustomCompendiumKey,
  getFocusPickerCustomCompendiumKeys,
  getTalentPickerCustomCompendiumKey,
  getTalentPickerCustomCompendiumKeys,
  getTalentPickerCustomFolderFilterEnabled,
} from "./pickerSettings.js";
